// export const CHOOSE_ADDING_ACTION = 'CHOOSE_ADDING_ACTION';
// export const ADD_NEW_CINEMA = 'ADD_NEW_CINEMA';
// export const ADD_NEW_MOVIE = 'ADD_NEW_MOVIE';
// export const ADD_NEW_SERVICES = 'ADD_NEW_SERVICES';
// export const ADD_NEW_SESSION = 'ADD_NEW_SESSION';

export const addingActions = {
  ADD_NEW_CINEMA: 'ADD_NEW_CINEMA',
  ADD_NEW_MOVIE: 'ADD_NEW_MOVIE',
  ADD_NEW_SERVICE: 'ADD_NEW_SERVICE',
  ADD_NEW_SESSION: 'ADD_NEW_SESSION',
};

export const deletingActions = {
  DELETE_CINEMA: 'DELETE_CINEMA',
  DELETE_MOVIE: 'DELETE_MOVIE',
  DELETE_SERVICE: 'DELETE_SERVICE',
  DELETE_SESSION: 'DELETE_SESSION',
};

export const changingActions = {
  CHANGE_CINEMA: 'CHANGE_CINEMA',
  CHANGE_MOVIE: 'CHANGE_MOVIE',
  CHANGE_SERVICE: 'CHANGE_SERVICE',
  CHANGE_SESSION: 'CHANGE_SESSION',
};
